// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NavigationItem struct {
	ID    string            `json:"id"`
	Name  string            `json:"name"`
	Link  string            `json:"link"`
	Items []*NavigationItem `json:"items"`
}
